version: '3.8'

services:

  stweb:
    build: ./app
    container_name: stweb
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 8081:8080
    env_file:
      - ./.env.dev
    depends_on:
      - stdb
  
  stcelery:
    build: ./app
    container_name: stcelery
    command: celery -A status_db worker --loglevel=INFO
    volumes:
      - media_volume:/usr/src/app/mediafiles
    env_file:
      - ./.env.dev
    depends_on:
      - stredis
      - stweb

  stdb:
    container_name: stdb
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=stdb_usr
      - POSTGRES_PASSWORD=stdb_usr_pwd
      - POSTGRES_DB=stdb
  
  stredis:
    image: redis:alpine
    container_name: stredis
    volumes:
      - ./redis_data:/data

volumes:
  postgres_data:
  media_volume:
