# Generated by Django 3.2.16 on 2022-11-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brockercontact',
            name='telegram',
            field=models.BooleanField(default=False, verbose_name='Есть в TG'),
        ),
        migrations.AlterField(
            model_name='linkedincontact',
            name='telegram',
            field=models.BooleanField(default=False, verbose_name='Есть в TG'),
        ),
        migrations.AlterField(
            model_name='propertycontact',
            name='telegram',
            field=models.BooleanField(default=False, verbose_name='Есть в TG'),
        ),
        migrations.AlterField(
            model_name='requestcontact',
            name='telegram',
            field=models.BooleanField(default=False, verbose_name='Есть в TG'),
        ),
        migrations.AlterField(
            model_name='tsumcontact',
            name='telegram',
            field=models.BooleanField(default=False, verbose_name='Есть в TG'),
        ),
        migrations.AlterField(
            model_name='villagecontact',
            name='telegram',
            field=models.BooleanField(default=False, verbose_name='Есть в TG'),
        ),
        migrations.AlterField(
            model_name='yacontact',
            name='telegram',
            field=models.BooleanField(default=False, verbose_name='Есть в TG'),
        ),
    ]
