# Generated by Django 3.2.16 on 2022-11-29 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20221130_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestcontact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'База заявок'},
        ),
    ]
