# Generated by Django 3.2.16 on 2022-12-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_requestcontact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcontact',
            name='source',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='propertycontact',
            name='company_field',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Деятельность'),
        ),
        migrations.AlterField(
            model_name='tsumcontact',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Название бренда'),
        ),
        migrations.AlterField(
            model_name='villagecontact',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Название поселка'),
        ),
    ]
