# Generated by Django 3.2.16 on 2022-12-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20221201_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertycontact',
            name='company_field',
        ),
        migrations.AddField(
            model_name='linkedincontact',
            name='company_field',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Деятельность'),
        ),
    ]
